apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: etcd
spec:
  serviceName: etcd-headless
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.9
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        env:
        - name: ETCD_NAME
          valueFrom:
            configMapKeyRef:
              name: etcd-config
              key: ETCD_NAME
        - name: ETCD_DATA_DIR
          valueFrom:
            configMapKeyRef:
              name: etcd-config
              key: ETCD_DATA_DIR
        - name: ETCD_LISTEN_CLIENT_URLS
          valueFrom:
            configMapKeyRef:
              name: etcd-config
              key: ETCD_LISTEN_CLIENT_URLS
        - name: ETCD_ADVERTISE_CLIENT_URLS
          valueFrom:
            configMapKeyRef:
              name: etcd-config
              key: ETCD_ADVERTISE_CLIENT_URLS
        - name: ETCD_LISTEN_PEER_URLS
          valueFrom:
            configMapKeyRef:
              name: etcd-config
              key: ETCD_LISTEN_PEER_URLS
        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          valueFrom:
            configMapKeyRef:
              name: etcd-config
              key: ETCD_INITIAL_ADVERTISE_PEER_URLS
        - name: ETCD_INITIAL_CLUSTER
          valueFrom:
            configMapKeyRef:
              name: etcd-config
              key: ETCD_INITIAL_CLUSTER
        - name: ETCD_INITIAL_CLUSTER_STATE
          valueFrom:
            configMapKeyRef:
              name: etcd-config
              key: ETCD_INITIAL_CLUSTER_STATE
        - name: ETCD_INITIAL_CLUSTER_TOKEN
          valueFrom:
            configMapKeyRef:
              name: etcd-config
              key: ETCD_INITIAL_CLUSTER_TOKEN
        - name: ETCD_AUTO_TLS
          valueFrom:
            configMapKeyRef:
              name: etcd-config
              key: ETCD_AUTO_TLS
        - name: ETCD_PEER_AUTO_TLS
          valueFrom:
            configMapKeyRef:
              name: etcd-config
              key: ETCD_PEER_AUTO_TLS
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd-data
        command:
        - /bin/sh
        - -c
        - |
          exec etcd
  volumeClaimTemplates:
  - metadata:
      name: etcd-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-service
  namespace: etcd
spec:
  selector:
    app: etcd
  ports:
  - port: 2379
    targetPort: 2379
    name: client
  - port: 2380
    targetPort: 2380
    name: peer
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-headless
  namespace: etcd
spec:
  clusterIP: None
  selector:
    app: etcd
  ports:
  - port: 2379
    targetPort: 2379
    name: client
  - port: 2380
    targetPort: 2380
    name: peer
