apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-config
  namespace: etcd
data:
  ETCD_NAME: "etcd-0"
  ETCD_DATA_DIR: "/etcd-data"
  ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
  ETCD_ADVERTISE_CLIENT_URLS: "http://etcd-service:2379"
  ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
  ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd-0.etcd-headless:2380"
  ETCD_INITIAL_CLUSTER: "etcd-0=http://etcd-0.etcd-headless:2380"
  ETCD_INITIAL_CLUSTER_STATE: "new"
  ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster-1"
  ETCD_AUTO_TLS: "false"
  ETCD_PEER_AUTO_TLS: "false"
