apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: openim-infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: bitnamilegacy/etcd:3.5.13
        ports:
        - containerPort: 2379
        - containerPort: 2380
        env:
        - name: ETCD_NAME
          value: "s1"
        - name: ETCD_DATA_DIR
          value: "/etcd-data"
        - name: ETCD_LISTEN_CLIENT_URLS
          value: "http://0.0.0.0:2379"
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: "http://etcd:2379"
        - name: ETCD_LISTEN_PEER_URLS
          value: "http://0.0.0.0:2380"
        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          value: "http://etcd:2380"
        - name: ETCD_INITIAL_CLUSTER
          value: "s1=http://etcd:2380"
        - name: ETCD_INITIAL_CLUSTER_TOKEN
          value: "tkn"
        - name: ETCD_INITIAL_CLUSTER_STATE
          value: "new"
        - name: ALLOW_NONE_AUTHENTICATION
          value: "no"
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd-data
      volumes:
      - name: etcd-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: openim-infrastructure
spec:
  selector:
    app: etcd
  ports:
  - port: 2379
    targetPort: 2379
    name: client
  - port: 2380
    targetPort: 2380
    name: peer
