apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: openim-infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2024-01-11T07-46-16Z
        ports:
        - containerPort: 9000
        - containerPort: 9090
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: MINIO_ROOT_USER
          value: "root"
        - name: MINIO_ROOT_PASSWORD
          value: "openIM123"
        command:
        - minio
        - server
        - /data
        - --console-address
        - ":9090"
        volumeMounts:
        - name: minio-data
          mountPath: /data
      volumes:
      - name: minio-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: openim-infrastructure
spec:
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
    name: api
  - port: 9090
    targetPort: 9090
    name: console
  type: LoadBalancer
