version: '3.8'

services:
  # 前端服务
  frontend:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro  # SSL证书目录
      - ./logs/nginx:/var/log/nginx  # 日志目录
    environment:
      - BACKEND_SERVER=${BACKEND_SERVER:-chat-service.default.svc.cluster.local:8080}
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - openim-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  openim-network:
    driver: bridge